# Generated by Django 4.2.13 on 2024-07-31 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArnasoyTuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INN', models.CharField(max_length=50)),
                ('COATO', models.CharField(max_length=50)),
                ('TASHKILOT_NOMI', models.TextField()),
                ('OKED', models.CharField(max_length=30)),
                ('COOGU', models.CharField(max_length=30)),
                ('BOLIM_NOMI', models.TextField()),
                ('LAVOZIM', models.TextField()),
                ('BOSH_ISH_ORIN_BIRLIGI', models.CharField(max_length=10)),
                ('NSKZ', models.CharField(max_length=30)),
                ('TELERAQAM1', models.CharField(max_length=30)),
                ('TELERAQAM2', models.CharField(max_length=30)),
                ('POCHTA_MANZIL', models.TextField()),
                ('BUDGET_0_XUSUSIY_1', models.CharField(max_length=10)),
                ('MAOSH', models.CharField(max_length=30)),
                ('LAVOZIMGA_QOYILGAN_TALABLAR', models.CharField(max_length=30)),
                ('SOXA', models.TextField()),
                ('XUDUD', models.TextField(default='Жиззах вилояти')),
                ('TUMAN', models.CharField(choices=[('Арнасой тумани', 'Арнасой тумани'), ('Бахмал тумани', 'Бахмал тумани'), ('Шароф Рашидов тумани', 'Ғаллаорол тумани'), ('Шароф Рашидов тумани', 'Шароф Рашидов тумани'), ('Дўстлик тумани', 'Дўстлик тумани'), ('Зомин тумани', 'Зомин тумани'), ('Зарбдор тумани', 'Зарбдор тумани'), ('Мирзачўл тумани', 'Мирзачўл тумани'), ('Зафаробод тумани', 'Зафаробод тумани'), ('Пахтакор тумани', 'Пахтакор тумани'), ('Фориш тумани', 'Фориш тумани'), ('Янгиобод тумани', 'Янгиобод тумани'), ('Жиззах', 'Жиззах')], default='Арнасой тумани', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BaxmalTumani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INN', models.CharField(max_length=50)),
                ('COATO', models.CharField(max_length=50)),
                ('TASHKILOT_NOMI', models.TextField()),
                ('OKED', models.CharField(max_length=30)),
                ('COOGU', models.CharField(max_length=30)),
                ('BOLIM_NOMI', models.TextField()),
                ('LAVOZIM', models.TextField()),
                ('BOSH_ISH_ORIN_BIRLIGI', models.CharField(max_length=10)),
                ('NSKZ', models.CharField(max_length=30)),
                ('TELERAQAM1', models.CharField(max_length=30)),
                ('TELERAQAM2', models.CharField(max_length=30)),
                ('POCHTA_MANZIL', models.TextField()),
                ('BUDGET_0_XUSUSИY_1', models.CharField(max_length=10)),
                ('MAOSH', models.CharField(max_length=30)),
                ('LAVOZIMGA_QOYILGAN_TALABLAR', models.CharField(max_length=30)),
                ('SOXA', models.TextField()),
                ('XUDUD', models.TextField(default='Жиззах вилояти')),
                ('TUMAN', models.CharField(choices=[('Арнасой тумани', 'Арнасой тумани'), ('Бахмал тумани', 'Бахмал тумани'), ('Шароф Рашидов тумани', 'Ғаллаорол тумани'), ('Шароф Рашидов тумани', 'Шароф Рашидов тумани'), ('Дўстлик тумани', 'Дўстлик тумани'), ('Зомин тумани', 'Зомин тумани'), ('Зарбдор тумани', 'Зарбдор тумани'), ('Мирзачўл тумани', 'Мирзачўл тумани'), ('Зафаробод тумани', 'Зафаробод тумани'), ('Пахтакор тумани', 'Пахтакор тумани'), ('Фориш тумани', 'Фориш тумани'), ('Янгиобод тумани', 'Янгиобод тумани'), ('Жиззах', 'Жиззах')], default='Бахмал тумани', max_length=100)),
            ],
        ),
    ]
