# Generated by Django 4.2.13 on 2024-07-31 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vakasibotapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baxmaltumani',
            old_name='BUDGET_0_XUSUSИY_1',
            new_name='BUDGET_0_XUSUSIY_1',
        ),
        migrations.AlterField(
            model_name='arnasoytuman',
            name='TUMAN',
            field=models.CharField(default='Арнасой тумани', max_length=100),
        ),
        migrations.AlterField(
            model_name='baxmaltumani',
            name='TUMAN',
            field=models.CharField(default='Бахмал тумани', max_length=100),
        ),
    ]
