# Generated by Django 4.2.13 on 2024-07-31 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vakasibotapp', '0003_dostiliktumani_forishtumani_gallaoroltumani_jizzax_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArnasoyTuman',
            new_name='ArnasoyTumani',
        ),
    ]
