# Generated by Django 4.2.13 on 2024-07-31 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vakasibotapp', '0004_rename_arnasoytuman_arnasoytumani'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arnasoytumani',
            name='XUDUD',
            field=models.CharField(default='Жиззах вилояти', max_length=100),
        ),
        migrations.AlterField(
            model_name='baxmaltumani',
            name='XUDUD',
            field=models.CharField(default='Жиззах вилояти', max_length=100),
        ),
        migrations.AlterField(
            model_name='dostiliktumani',
            name='XUDUD',
            field=models.CharField(default='Жиззах вилояти', max_length=100),
        ),
        migrations.AlterField(
            model_name='forishtumani',
            name='XUDUD',
            field=models.CharField(default='Жиззах вилояти', max_length=100),
        ),
        migrations.AlterField(
            model_name='gallaoroltumani',
            name='XUDUD',
            field=models.CharField(default='Жиззах вилояти', max_length=100),
        ),
        migrations.AlterField(
            model_name='jizzax',
            name='XUDUD',
            field=models.CharField(default='Жиззах вилояти', max_length=100),
        ),
        migrations.AlterField(
            model_name='mirzacholtumani',
            name='XUDUD',
            field=models.CharField(default='Жиззах вилояти', max_length=100),
        ),
        migrations.AlterField(
            model_name='paxtakortumani',
            name='XUDUD',
            field=models.CharField(default='Жиззах вилояти', max_length=100),
        ),
        migrations.AlterField(
            model_name='sharofrashidovtumani',
            name='XUDUD',
            field=models.CharField(default='Жиззах вилояти', max_length=100),
        ),
        migrations.AlterField(
            model_name='yangiobodtumani',
            name='XUDUD',
            field=models.CharField(default='Жиззах вилояти', max_length=100),
        ),
        migrations.AlterField(
            model_name='zafarobodtumani',
            name='XUDUD',
            field=models.CharField(default='Жиззах вилояти', max_length=100),
        ),
        migrations.AlterField(
            model_name='zarbdortumani',
            name='XUDUD',
            field=models.CharField(default='Жиззах вилояти', max_length=100),
        ),
        migrations.AlterField(
            model_name='zomintumani',
            name='XUDUD',
            field=models.CharField(default='Жиззах вилояти', max_length=100),
        ),
    ]
