# Generated by Django 4.2.13 on 2024-07-31 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vakasibotapp', '0005_alter_arnasoytumani_xudud_alter_baxmaltumani_xudud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arnasoytumani',
            name='TUMAN',
        ),
        migrations.RemoveField(
            model_name='baxmaltumani',
            name='TUMAN',
        ),
        migrations.RemoveField(
            model_name='dostiliktumani',
            name='TUMAN',
        ),
        migrations.RemoveField(
            model_name='forishtumani',
            name='TUMAN',
        ),
        migrations.RemoveField(
            model_name='gallaoroltumani',
            name='TUMAN',
        ),
        migrations.RemoveField(
            model_name='jizzax',
            name='TUMAN',
        ),
        migrations.RemoveField(
            model_name='mirzacholtumani',
            name='TUMAN',
        ),
        migrations.RemoveField(
            model_name='paxtakortumani',
            name='TUMAN',
        ),
        migrations.RemoveField(
            model_name='sharofrashidovtumani',
            name='TUMAN',
        ),
        migrations.RemoveField(
            model_name='yangiobodtumani',
            name='TUMAN',
        ),
        migrations.RemoveField(
            model_name='zafarobodtumani',
            name='TUMAN',
        ),
        migrations.RemoveField(
            model_name='zarbdortumani',
            name='TUMAN',
        ),
        migrations.RemoveField(
            model_name='zomintumani',
            name='TUMAN',
        ),
    ]
